'pdb_root': '/data2/csz/PPI_tnnls/data/data_pdb/cath43/'
'graph_root': '/data2/csz/PPI_tnnls/data/'
'num_layers': 4
'hidden_dim': 256
'input_dim': 7
'heads': 4
'mask_rate': 0.2
'num_embeddings': 512
'commitment_cost': 0.25
'remask_rate': 0.2
'num_masking': 3
'embedding_dim': 256
'alpha_l': 3
'batch_size': 64
'dataname': 'CATH43'
'pre_epoch': 50
'lr': 0.00001