'pdb_root': '/data2/csz/PPI_tnnls/String_data/raw_data/STRING_AF2DB/'
'graph_root': '/data2/csz/PPI_tnnls/data/'
'prot_num_layers': 4
'hidden_dim': 256
'input_dim': 7
'heads': 4
'mask_rate': 0.4
'num_embeddings': 256
'commitment_cost': 0.25
'remask_rate': 0.2
'num_masking': 3
'embedding_dim': 256
'alpha_l': 3
'batch_size': 64
'data_name': 'SHS148k'
'pre_epoch': 50
'learning_rate': 0.001
'weight_decay': 0.0001
'dropout_ratio': 0.3
'prot_hidden_dim': 256
'mask_ratio': 0.15
'sce_scale': 2

'radius': 14
'topk': 15
'hops': 2
'split_mode': 'dfs'
'GIN_layers': 4
'dropout': 0.3
'epoch': 600
'output_dim': 7